### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by farao**

### CODE REVIEW

**Comment by farao** [comment]
@erikzenker + @paulgoetze: Thanks for helping with a big step for the signal tower this year! Is the CHANGELOG missing something that you would like mentioned? Or is the release missing some feature that we should wait for?

**Comment by paulgoetze** [comment]
Thanks, @farao. When looking through the changes (https://github.com/palavatv/signaltower/compare/v1.1.0...master), it might be worth mentioning that PALAVA_RTC_ADDRESS option was renamed to SIGNALTOWER_PORT? The new setup is also documented in the readme, still it could be good to state that it was different in the version before.

Do you think it's important to mention that the Websocket timeout was reduced from 40 to 30 sec, or is this not of interest?

Apart from that: :+1:. I'm all for releasing 2.0.0 and adding other potential refactorings or additions in subsequent minor versions.

**Comment by farao** [comment]
Yes, thanks, I added the renaming of the option to the changelog. I think reducing the seconds to 30 is not that important

**Review by erikzenker — APPROVED** [review]
Lgtm

**Pull request merged**
